### ISSUE TITLE
Requirements | Priority[Urgent]

### ISSUE THREAD

**Issue by XFarooqi** [GDSC-COMSATS-Sahiwal/tegathon#26]
Hy Team, 

The website is super amazing and futuristic, you folks did justice to this cool website. Can you please add the following as first priority:

1. Code of Conduct (Example: https://devhack.org/codeofconduct)
2. Add me to the team section
3. Updated Social handles on website 

Thanks

**Comment by nabeelahmedjh** [comment]
@shahzaib-ai

**Comment by shahzaib-ai** [comment]
I'll start working on it.

Edit: 
2 and 3 are done

**Comment by shahzaib-ai** [comment]
Added 1, 2, and 3
See preview here: https://tegathon-pi.vercel.app/
